Repository owncloud/docs-webui, pull requests merged in 2022-06, with the labels that each got.

#43 Web UI for admins
  modules/owncloud_web/images/create-user.png
  modules/owncloud_web/images/user-management.png
  modules/owncloud_web/pages/web_for_admins.adoc
  modules/owncloud_web/partials/nav.adoc
Labels: documentation

#44 Harmonisation of site.yml
  site.yml
Labels: deployment

#45 Adding Web app configuration
  modules/owncloud_web/images/application-switcher-oc10.jpg
  modules/owncloud_web/pages/web_with_oC10.adoc
Labels: documentation, owncloud_web

#47 Small fixes
  modules/owncloud_web/pages/web_with_oC10.adoc
Labels: documentation
