Repository owncloud/docs-webui, pull requests merged in 2022-04, with the labels that each got.

#22 Update deleted_file_management.adoc
  modules/classic_ui/pages/files/deleted_file_management.adoc
Labels: bug

#23 first draft of ownCloud Web doc
  modules/owncloud_web/pages/index.adoc
  modules/owncloud_web/pages/web_for_admins.adoc
  modules/owncloud_web/pages/web_for_users.adoc
  modules/owncloud_web/pages/web_with_oC10.adoc
  modules/owncloud_web/partials/nav.adoc
Labels: documentation, owncloud_web

#24 more on sharing and the right sidebar
  modules/owncloud_web/pages/index.adoc
  modules/owncloud_web/pages/web_for_users.adoc
Labels: documentation

#25 layout fixes
  modules/owncloud_web/pages/web_for_users.adoc
Labels: documentation

#26 update site.yml
  site.yml
Labels: deployment
