Repository owncloud/docs-webui, pull requests merged in 2022-07, with the labels that each got.

#52 turning web configuration into a partial
  modules/owncloud_web/pages/web_with_oC10.adoc
  modules/owncloud_web/partials/web-configuration.adoc
Labels: documentation

#53 Theming description for ownCloud Web
  modules/owncloud_web/pages/themed_webui.adoc
  modules/owncloud_web/partials/nav.adoc
Labels: documentation, owncloud_web

#55 Fixing the user search documentation (ownCloud classic)
  modules/classic_ui/pages/files/webgui/search.adoc
Labels: classic_ui

#62 Update the WebUI intro page
  modules/ROOT/pages/index.adoc
  modules/classic_ui/images/files_page.png
Labels: documentation

#63 Reduce image filesizes
  modules/ROOT/pages/index.adoc
Labels: documentation

#64 Image Crop
  modules/classic_ui/images/files_page.png
Labels: documentation

#67 Update ownCloud Web for Users
  modules/owncloud_web/images/sidebar.png
  modules/owncloud_web/pages/web_for_users.adoc
Labels: documentation
